### ISSUE TITLE
 [RFE] Verify if ingress controller is up & running prior running a workload with routes

### ISSUE THREAD

**Issue by rsevilla87** [kube-burner/kube-burner#408]
**Is your feature request related to a problem? Please describe.**
Similar to https://github.com/cloud-bulldozer/kube-burner/issues/389 we can add this feature for workloads creating routes

**Describe the solution you'd like**
It should only affect the OCP wrapper workloads having routes among their objects

**Additional context**
Having the ingress controller properly configured should be a pre-requirement to trigger some workloads, like cluster-density-v2

**Comment by jdowni000** [comment]
@rsevilla87 is this already being achieved with [pr](https://github.com/cloud-bulldozer/kube-burner/pull/406) ? It looks like the new function `VerifyContainerRegistry` now runs in every variation of `NewClusterDensity` if this PR is merged. This would include cluster-density-v2 and cluster-density-ms? I am new to the project so please forgive if I am misunderstanding something.

**Comment by rsevilla87** [comment]
> @rsevilla87 is this already being achieved with [pr](https://github.com/cloud-bulldozer/kube-burner/pull/406) ? It looks like the new function `VerifyContainerRegistry` now runs in every variation of `NewClusterDensity` if this PR is merged. This would include cluster-density-v2 and cluster-density-ms? I am new to the project so please forgive if I am misunderstanding something.

The PR you mentioned is meant to verify the internal registry is up & running for OCP workloads deploying builds and buildconfigs such as cluster-density and its variants.

The issue described here is to check the ingress-controller (not for the internal registry) and verify it's available for workloads using routes (iirc only cluster-density-v2 is currently using them)

**Comment by rsevilla87** [comment]
> This ^ did not enter any kube-burner release yet, correct? I am monitoring #389 (now moved here) to update kube-burner in another tooling we have.

Hey @sferlin, this issue is still pending and development hasn't been started yet AFAIK, on the other hand https://github.com/cloud-bulldozer/kube-burner/issues/389 is already available in [v1.7.6 ](https://github.com/cloud-bulldozer/kube-burner/releases/tag/v1.7.6)

**Comment by rsevilla87** [comment]
This issue is being worked at https://github.com/kube-burner/kube-burner/issues/568, closing
