### ISSUE TITLE
[RFE] Flag to pass kube context to kube burner explicitly

### ISSUE THREAD

**Issue by Nick-Triller** [kube-burner/kube-burner#535]
**Is your feature request related to a problem? Please describe.**
Setting current k8s context so that kube-burner uses the correct cluster is unergonomic and potentially dangerous.

**Describe the solution you'd like**
I would like a flag that allows setting the k8s context that should be used by kube burner explicitly. The flag can be optional, with the current behaviour if the flag isn't set.

**Comment by rsevilla87** [comment]
I don't think this feature is necessary, context should be set upfront by the user and is out of scope kube-burner, as far as I know most of CLI tools of the k8s ecosystem don't have anything like this.

**Comment by Nick-Triller** [comment]
@rsevilla87 I am fine with that decision, but it is a common feature for CLI tools in the k8s ecosystem. For example, kubectl has `--context`, helm has `--kube-context`, k9s has `--context` etc.

Kubernetes client-go library has explicit support for overwriting the current context when loading a kubeconfig:
```go
overrides := &clientcmd.ConfigOverrides{
  CurrentContext: kubeContext,
}
configLoadingRules := &clientcmd.ClientConfigLoadingRules{ExplicitPath: kubeconfigPath}
restConfig, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(configLoadingRules, overrides).ClientConfig()
```

**Comment by rsevilla87** [comment]
> Kubernetes client-go library has explicit support for overwriting the current context when loading a kubeconfig:

ok, I don't have much cycles now, but feel free to add this feature yourself, shouldn't be very complex, we'll review it asap

**Comment by smalleni** [comment]
@Nick-Triller Hey, just checking in if you;d be interested to contribute and needed any help?

**Comment by Nick-Triller** [comment]
Hi @smalleni, I am not planning to work on this issue because of lack of time

**Comment by hhiroshell** [comment]
Hi @smalleni and @rsevilla87,

Is it okay if I try implementing this feature? I'm interested in it as well.

I think directly mimicking the kubectl flags might lead to confusion when they are listed alongside flags that kube-burner already has. So, I intend to start by considering the specifications for this aspect.

**Comment by rsevilla87** [comment]
> are listed alongside

Hey @hhiroshell, I'd personally prefer to mimic the kubectl flags, `--kubeconfig` and '--context'  if possible, I can't see any conflict or confusion with the flags that `kube-burner init`, `kube-burner destroy` or `kube-burner measure` already provide

**Comment by hhiroshell** [comment]
Hi @rsevilla87 

Let me elaborate on my concerns in more detail.

Besides `--context`, kubectl also includes `--username` and `--namespace` flags that modify a portion of the context settings.
Therefore, if kube-burner introduces a `--context` flag, it might leads users to expect kube-burner's `--username` and `--namespace` flags to function the same as kubectl's.

**Comment by hhiroshell** [comment]
@rsevilla87 
I have created a PR for this issue. Could you please review it?

https://github.com/kube-burner/kube-burner/pull/604
