### ISSUE TITLE
[RFE] ES auth

### ISSUE THREAD

**Issue by riuvshyn** [kube-burner/kube-burner#571]
Hello, thanks for creating great tool!
I was wondering how do I configure auth for accessing ES instance?
I do not see anything in docs around Auth. 
Thanks!

cc @rsevilla87 🙏🏽

**Comment by jtaleric** [comment]
Hey @riuvshyn we usually pass auth via the URL, like 

`https://user:pass@opensearch.server.com`

**Comment by rsevilla87** [comment]
Documented at https://kube-burner.github.io/kube-burner/latest/observability/indexing/#elasticopensearch

**Comment by riuvshyn** [comment]
oh, my bad. sorry and thanks a lot for looking into this!
