### ISSUE TITLE
[RFE] Point out churning start date in indexed documents

### ISSUE THREAD

**Issue by rsevilla87** [kube-burner/kube-burner#594]
**Is your feature request related to a problem? Please describe.**

To improve benchmark's result analysis, we need to be able to rule out the collected metrics during churning stage.

**Describe the solution you'd like**

Several changes will be needed:

- As part of the `jobSummary` metric we currently generate

https://github.com/kube-burner/kube-burner/blob/69cbf3c694879f140d1a6acbf38f130a73b6f0fd/pkg/burner/metadata.go#L33-L40

Add a new field to this document to indicate the churning stage start date.

- In the Prometheus/measurement/alerts based indexed results, add an extra (`churning: false/true`?) field to indicate they were collected during the churning stage or not

Once we've these fields we should be able to rule out metrics of churning stage of a benchmark.

**Additional context**

This feature popped up in today's meeting as analyzing metrics for benchmarks with churning can be challenging since their results can be misleading, ie the duration of namespace removal has lot of variation.

cc: @kube-burner/ocp-perfscale @kube-burner/ocp-perfscale-telco

**Comment by vishnuchalla** [comment]
Just to check if my understanding is correct from an implementation perspective, so we want to keep track of start and end times of all the churn cycles and mark all the Prometheus data-points that fall in between those intervals as churn metrics. Does that sound good?
Also along with the start time of churn, do we also want to publish the end time of churn in the `jobSummary`? Because benchmark end time is not same as churn end time as we have some sleep delay [here](https://github.com/kube-burner/kube-burner/blob/main/pkg/burner/create.go#L375).

**Comment by rsevilla87** [comment]
> Just to check if my understanding is correct from an implementation perspective, so we want to keep track of start and end times of all the churn cycles and mark all the Prometheus data-points that fall in between those intervals as churn metrics. Does that sound good? Also along with the start time of churn, do we also want to publish the end time of churn in the `jobSummary`? Because benchmark end time is not same as churn end time as we have some sleep delay [here](https://github.com/kube-burner/kube-burner/blob/main/pkg/burner/create.go#L375).

correct, adding an extra field `churning: true/false` to the indexed documents falling between churning/not-churning intervals should be the correct way.

wrt the second question, `churningDelay` is something that happens during the churning stage, so I think we should include it. 
Churning start/end dates should be taken before/after calling this function:

https://github.com/kube-burner/kube-burner/blob/69cbf3c694879f140d1a6acbf38f130a73b6f0fd/pkg/burner/job.go#L155-L157
