### ISSUE TITLE
[RFE] Optional -start instant queries

### ISSUE THREAD

**Issue by rsevilla87** [kube-burner/kube-burner#603]
**Is your feature request related to a problem? Please describe.**

With the current logic, when kube-burner scrapes an instant query, it generates at least two documents, one uses the start timestamp and the latter the end timestamp of the job. It is not always necessary to capture the `-start` metric, as this metric normally makes sense when applied to metrics that normally get increased over time.

**Describe the solution you'd like**

Add an extra field to the metricsProfile, ie: `captureStart: true/false` (false by default), to specify which metrics we want to capture capture from the start of the job.

cc: @afcollins

**Comment by afcollins** [comment]
Thanks for including me. I know I pushed for the start and end metrics. :)

I agree that it may not always be necessary to capture the start metric, but do we want to not capture it by default? I suppose the cases could be more frequent that don't need the start metric.
