### ISSUE TITLE
[RFE] Use multi-arch container images for perfapp and pause 

### ISSUE THREAD

**Issue by varad-ahirwadkar** [kube-burner/kube-burner#605]
**Is your feature request related to a problem? Please describe.**
While running kube-burner tests on an OCP multi-architecture cluster with both ppc64le and amd64 architectures, the kubelet-density-heavy PerfApp pods were failing due to incompatible images. -
 https://github.com/kube-burner/kube-burner/blob/ee483d95fe6e707f09cab2d176089c27549a59f1/examples/workloads/kubelet-density-heavy/templates/app-deployment.yml#L15

Additionally, In some scenarios, pre-load pods failed because of an incompatible image for the pause container.
https://github.com/kube-burner/kube-burner/blob/ee483d95fe6e707f09cab2d176089c27549a59f1/pkg/burner/pre_load.go#L134 

**Describe the solution you'd like**
Following images can be used:
perfapp: quay.io/cloud-bulldozer/perfapp:latest
pause: registry.k8s.io/pause:3.1

**Comment by krishvoor** [comment]
> > @varad-ahirwadkar As Raul pointed can you submit a multi-arch PR for here PerfApp: https://github.com/cloud-bulldozer/images/tree/main/perfapp
> 
> As Varad already noted, we just need to update the images location, quay.io/cloud-bulldozer/perfapp:latest and registry.k8s.io/pause:3.1 have multi-arch containers

Silly me, I checked `rsevilla` repo and figured it was not multi-arch ;-)

**Comment by varad-ahirwadkar** [comment]
> Thanks for raising this up, can you file a PR to update the affected files?, Thanks!

Hi @rsevilla87 @krishvoor , I have opened a PR. 

Thanks

**Comment by rsevilla87** [comment]
Closed by #607
