### ISSUE TITLE
[BUG] kube-burner#611 reverted appending UUID to local metrics dir

### ISSUE THREAD

**Issue by afcollins** [kube-burner/kube-burner#634]
# Bug Description
When indexing locally, the UUID was appended to the local dir so recurring runs would not overwrite one another.

kube-burner#611 reverted this behavior.

## **Output of `kube-burner` version**

v1.9.6

## **Describe the bug**

Local indexing is all written to the same directory now.

## **To Reproduce**

1. Configure job with a local indexer.
2. Local indexing written to `collected-metrics/`.

## **Expected behavior**

Local indexing written to `collected-metrics-${UUID}/`.

**Comment by vishnuchalla** [comment]
This option is configurable and I see all ocp-wrapper jobs creating unique UUID. If a users uses this repository to run on vanilla k8s, they still have the option to configure metircs directory in their indexer config or else it will fallback to the [default](https://github.com/kube-burner/kube-burner/blob/main/pkg/config/config.go#L55) value which should be fine. Please feel free to reopen it, if we still need an automatic UUID append to the `collected-metrics` dir in this core repo.
