### ISSUE TITLE
[BUG] Pod Latency of 13.5s reported

### ISSUE THREAD

**Issue by afcollins** [kube-burner/kube-burner#645]
# Bug Description

## **Output of `kube-burner` version**
```
time="2024-05-27 14:30:03" level=info msg="🔥 Starting kube-burner (1.2.5@cb1ab00da9b17167fef0a0aa6318ec6f70fc8bee) with UUID 4f5da9d6-81e4-4826-a3b0-787e831e2eec" file="job.go:99"
```

## **Describe the bug**
Since we fixed the fake millisecond precision issue, pod latencies are reported as whole numbers in increments of 1000 (1000 milliseconds = 1 second).
Quantiles calculated have since also been in clean multiples of 1000.

A run came through recently that had p99=13500ms.
Wondering whether some change was introduced to quantile calculation that we can expect this behavior going forward.

## **Expected behavior**

Pod Latency quantiles are increments of 1000.

## **Screenshots or output**

```
time="2024-05-27 14:56:34" level=info msg="cluster-density-v2: ContainersReady 50th: 4000 99th: 13500 max: 25000 avg: 5858" file="pod_latency.go:242"
```

## **Additional context**
[slack thread](https://redhat-internal.slack.com/archives/C05CDC19ZKJ/p1716841903078189)

**Comment by vishnuchalla** [comment]
Closing it as it is a normal expected calculation. Please feel free to reopen it. Reference code block: https://github.com/montanaflynn/stats/blob/master/percentile.go#L8
