### ISSUE TITLE
[RFE] OCP-CI for ppc64le for release testing

### ISSUE THREAD

**Issue by varad-ahirwadkar** [kube-burner/kube-burner#646]
**Is your feature request related to a problem? Please describe.**
There is no release testing CI for kube-burner `ppc64le` binary.

**Describe the solution you'd like**
ppc64le CI for release testing prior publishing the binaries.

**Comment by krishvoor** [comment]
Thanks for your proposal @varad-ahirwadkar.
We run kind clusters for the kube-burner/kube-burner repository CI tests on:
https://github.com/kube-burner/kube-burner/blob/main/.github/workflows/test-k8s.yml#L50-L53

**Comment by kishen-v** [comment]
Update:
We have made the required changes to enable CI and have tested the GH workflow to have a ppc64le self-hosted runner. The request for a VM has been raised and we're currently awaiting access to it.

Looking forward to enabling k8s kube-burner CI on ppc64le, as the first step before we continue with the OCP CI.

Thanks!
