### ISSUE TITLE
[BUG] kubelet-node-density-heavy example issue

### ISSUE THREAD

**Issue by jtaleric** [kube-burner/kube-burner#649]
# Bug Description
jtaleric at polaris in ~/code/kube-burner/examples/workloads/kubelet-density-heavy on main* $ ../../../bin/amd64/kube-burner init -c kubelet-density-heavy.yml 
time="2024-06-06 13:48:04" level=fatal msg="Config error: error decoding configuration file: yaml: line 1: did not find expected key" file="kube-burner.go:115"

## **Output of `kube-burner` version**
Built locally `Starting kube-burner (main@20073faf58208b86475838b9f2a5b6be98605597)`
## **Describe the bug**
Unable to run example.

**Comment by afcollins** [comment]
Another error reported with the examples in this [thread](https://kubernetes.slack.com/archives/C06EEGHTNJ1/p1717781157477089?thread_ts=1715705390.487889&cid=C06EEGHTNJ1).

I feel this issue could be generalized to "make sure the examples work".

**Comment by rsevilla87** [comment]
> Another error reported with the examples in this [thread](https://kubernetes.slack.com/archives/C06EEGHTNJ1/p1717781157477089?thread_ts=1715705390.487889&cid=C06EEGHTNJ1).
> 
> I feel this issue could be generalized to "make sure the examples work".

correct, we don't usually check for examples compatibility with the changes, I'll spend some time updating them accordingly,

**Comment by rsevilla87** [comment]
I haven't been able to reproduce the issue using latest version, can you verify it?
