### ISSUE TITLE
[BUG] vmiLatency measurement fails for delete jobs

### ISSUE THREAD

**Issue by jeniferh** [kube-burner/kube-burner#658]
# Bug Description
When running the example kubevirt-density workload, the vmiLatency measurement will throw an error for idle-job or delete-job, but works fine for the create job type.

## **Output of `kube-burner` version**
Version: 1.10.0
Git Commit: 1b9c7446fff5605724f0d8f72c38d855112e9b2a
Build Date: 2024-06-24T16:11:46Z
Go Version: go1.21.11
OS/Arch: linux amd64

## **Describe the bug**
 There is no error when the podLatency measurement is used for the `jobType: delete` kubevirt-density jobs

These jobs do disable the measurement collection:
`VMI latency measurement not compatible with delete jobs, skipping" file="vmi_latency.go:283`

However StopWatcher hits issues when the vmiLatency measurement is defined for the "delete" type.

## **To Reproduce**

Run the example kubevirt-density workload, ex: 
OBJ_REPLICAS=10  KUBECONFIG=/root/kubeconfig-test1 /root/kubevirt/kube-burner/kube-burner init  -c kubevirt-density.yml

## **Expected behavior**
vmiLatency does not error for delete

## **Screenshots or output**

Error messages:

```
time="2024-06-28 14:30:23" level=info msg="Job idle-job took 1m0s" file="job.go:196"
time="2024-06-28 14:30:23" level=info msg="Stopping measurement: vmiLatency" file="factory.go:125"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a948a6]

goroutine 75 [running]:
github.com/kube-burner/kube-burner/pkg/measurements/metrics.(*Watcher).StopWatcher(0x0)
	/home/runner/work/kube-burner/kube-burner/pkg/measurements/metrics/watcher.go:69 +0x86
github.com/kube-burner/kube-burner/pkg/measurements.(*vmiLatency).stop.func1()
	/home/runner/work/kube-burner/kube-burner/pkg/measurements/vmi_latency.go:386 +0x25
github.com/kube-burner/kube-burner/pkg/measurements.(*vmiLatency).stop(0x3627360?)
	/home/runner/work/kube-burner/kube-burner/pkg/measurements/vmi_latency.go:391 +0x82
github.com/kube-burner/kube-burner/pkg/measurements.Stop()
	/home/runner/work/kube-burner/kube-burner/pkg/measurements/factory.go:126 +0x148
github.com/kube-burner/kube-burner/pkg/burner.Run.func1()
	/home/runner/work/kube-burner/kube-burner/pkg/burner/job.go:199 +0x1853
created by github.com/kube-burner/kube-burner/pkg/burner.Run in goroutine 1
	/home/runner/work/kube-burner/kube-burner/pkg/burner/job.go:101 +0x634

[...]

time="2024-06-28 14:27:17" level=info msg="Job delete-job took 1m14s" file="job.go:196"
time="2024-06-28 14:27:17" level=info msg="Stopping measurement: vmiLatency" file="factory.go:125"
panic: close of closed channel

goroutine 10 [running]:
github.com/kube-burner/kube-burner/pkg/measurements/metrics.(*Watcher).StopWatcher(0xc0007a1110)
	/home/runner/work/kube-burner/kube-burner/pkg/measurements/metrics/watcher.go:73 +0xfe
github.com/kube-burner/kube-burner/pkg/measurements.(*vmiLatency).stop.func1()
	/home/runner/work/kube-burner/kube-burner/pkg/measurements/vmi_latency.go:386 +0x25
github.com/kube-burner/kube-burner/pkg/measurements.(*vmiLatency).stop(0x3627360?)
	/home/runner/work/kube-burner/kube-burner/pkg/measurements/vmi_latency.go:391 +0x82
github.com/kube-burner/kube-burner/pkg/measurements.Stop()
	/home/runner/work/kube-burner/kube-burner/pkg/measurements/factory.go:126 +0x148
github.com/kube-burner/kube-burner/pkg/burner.Run.func1()
	/home/runner/work/kube-burner/kube-burner/pkg/burner/job.go:199 +0x1853
created by github.com/kube-burner/kube-burner/pkg/burner.Run in goroutine 1
	/home/runner/work/kube-burner/kube-burner/pkg/burner/job.go:101 +0x634`

```

**Comment by rsevilla87** [comment]
Hey @jeniferh , thanks for opening this issue, glad to see there's some interest in the integration of kube-burner with kubevirt, it hasn't been upated in a while, so more issues are possible :(

I think I've found the issue and had pushed the fix in https://github.com/kube-burner/kube-burner/pull/659, I don't have a cluster with virtualization handy, can you help me to test the fix works correctly?

Thanks!

**Comment by jeniferh** [comment]
Yeah I am running some VM+PVC workloads, its great to be able to standardize on kube-burner to compare the API load vs other workloads types like cluster-density-v2. 

Thanks for such a quick turnaround @rsevilla87! I tested your PR and the vmiLatency measurement now works fine for delete jobs w/ that fix:
```
time="2024-07-01 17:04:39" level=info msg="Job delete-job took 5m14s" file="job.go:196"
time="2024-07-01 17:04:39" level=info msg="Stopping measurement: vmiLatency" file="factory.go:125"
time="2024-07-01 17:04:39" level=info msg="Indexing collected data from measurement: vmiLatency" file="factory.go:137"
```

**Comment by rsevilla87** [comment]
Great, we'll try to merge the PR and cut a new release asap
