### ISSUE TITLE
[BUG] VMI measurements are not collected if the VMI template does not include any labels

### ISSUE THREAD

**Issue by ygalblum** [kube-burner/kube-burner#736]
# Bug Description

If the VMI template does not include any labels, VMI measurements are not collected

## **Output of `kube-burner` version**

Version: 1.10.9
Git Commit: 14132166a0f6c276454a529cabfbf5b0ad36720a
Build Date: 2024-10-16T11:09:49Z
Go Version: go1.21.13
OS/Arch: darwin arm64

## **Describe the bug**

If the VMI template does not include any labels, VMI measurements are not collected

## **To Reproduce**

1. Use `kube-burner` to create a VM without setting any labels in the VMI template object
2. Make sure to add `vmiLatency` messurement

## **Expected behavior**

VMI measurements exist

## **Screenshots or output**

No VMI measurements

**Comment by rsevilla87** [comment]
ok, so the issue is that the injected runid label from the vmi is not being copied to the vm object, correct?

**Comment by ygalblum** [comment]
> ok, so the issue is that the injected runid label from the vmi is not being copied to the child vm object, correct?

Yes (along with the rest of the labels)
